---

version: "3"

services:
  nodejs:
    image: nodejs
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    container_name: frontend

---
